use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    // Setting any rerun-if-changed disables Cargo's implicit watch on build.rs itself,
    // so we have to declare it back explicitly.
    println!("cargo:rerun-if-changed=build.rs");
    // Directory-level watch catches add/remove/rename of toolchain scripts; per-file
    // watches below catch in-place edits to existing scripts.
    println!("cargo:rerun-if-changed=toolchains");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let toolchains_dir = PathBuf::from(&manifest_dir).join("toolchains");

    let read_dir = fs::read_dir(&toolchains_dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", toolchains_dir.display()));

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    for entry in read_dir {
        let entry = entry.expect("dir entry");
        let file_name = entry
            .file_name()
            .into_string()
            .expect("toolchains/ filenames must be utf-8");

        if file_name.starts_with('.') {
            continue;
        }

        let name = file_name.strip_suffix("-install.sh").unwrap_or_else(|| {
            panic!("toolchains/{file_name}: every file must be `<name>-install.sh`")
        });

        if name.is_empty()
            || !name
                .chars()
                .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit())
        {
            panic!(
                "toolchains/{file_name}: name {name:?} must be lowercase ASCII letters/digits"
            );
        }

        let path = entry.path();
        println!("cargo:rerun-if-changed={}", path.display());
        entries.push((name.to_string(), path));
    }

    if entries.is_empty() {
        panic!(
            "{}: no installer scripts found; the launcher needs at least one toolchains/<name>-install.sh",
            toolchains_dir.display()
        );
    }

    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("embedded_installers.rs");

    let mut content = String::from(
        "// Auto-generated by build.rs from toolchains/. Do not edit.\n\
         pub const INSTALLERS: &[(&str, &[u8])] = &[\n",
    );
    for (name, path) in &entries {
        let path_str = path.to_str().expect("toolchain path must be utf-8");
        content.push_str(&format!(
            "    ({:?}, include_bytes!({:?})),\n",
            name, path_str
        ));
    }
    content.push_str("];\n\npub const VALID_TOOLCHAINS: &[&str] = &[\n");
    for (name, _) in &entries {
        content.push_str(&format!("    {:?},\n", name));
    }
    content.push_str("];\n");

    fs::write(&dest, content).expect("write embedded_installers.rs");
}
