use std::fs;

use assert_cmd::Command;
use tempfile::tempdir;

const MALFORMED: &str = "toolchains:\n  dotnet: \"10.0\"\nextras: [unclosed\n";
const VALID: &str = "toolchains: {}\n";
const EXPECTED_DOCKERFILE: &str = "\
# Generated by pithos — do not edit
# Base stage: Debian bookworm-slim with Node, Python, uv, Pi CLI, and common dev tools pre-installed.
FROM ghcr.io/anton-kochev/pithos:base AS base
USER root

# Pi-config defaults baked into /opt/pi-defaults/; entrypoint seeds them into the user's volume on first run. Tini handles PID 1 signal forwarding.
COPY pi-config/ /opt/pi-defaults/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
USER pi
ENTRYPOINT [\"/usr/bin/tini\", \"--\", \"/usr/local/bin/entrypoint.sh\"]
CMD [\"pi\"]
";

#[test]
fn cli_exit_2_on_parse_error() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), MALFORMED).unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(2);

    // Assert
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("line "),
        "stderr missing 'line N' phrase: {stderr}"
    );
}

#[test]
fn cli_reads_from_cwd() {
    // Arrange
    let good = tempdir().unwrap();
    let bad = tempdir().unwrap();
    fs::write(good.path().join(".pithos"), VALID).unwrap();
    fs::write(bad.path().join(".pithos"), MALFORMED).unwrap();

    // Act
    let good_code = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&good)
        .assert()
        .get_output()
        .status
        .code();
    let bad_code = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&bad)
        .assert()
        .get_output()
        .status
        .code();

    // Assert
    assert_eq!(good_code, Some(0), "valid config should exit 0");
    assert_eq!(bad_code, Some(2), "malformed config should exit 2");
}

#[test]
fn cli_exit_2_when_pithos_missing_with_minimal_example_hint() {
    // Arrange
    let td = tempdir().unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(2);

    // Assert
    let output = assert.get_output();
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains(".pithos not found"),
        "stderr missing '.pithos not found' phrase: {stderr}"
    );
    assert!(
        stderr.contains("toolchains: {}"),
        "stderr missing 'toolchains: {{}}' minimal example: {stderr}"
    );
    assert!(
        output.stdout.is_empty(),
        "stdout should be empty, got: {:?}",
        String::from_utf8_lossy(&output.stdout)
    );
}

#[test]
fn cli_exit_2_on_missing_toolchains() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), "{}\n").unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(2);

    // Assert
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("missing required key"),
        "stderr missing 'missing required key' phrase: {stderr}"
    );
    assert!(
        stderr.contains("toolchains"),
        "stderr missing 'toolchains' phrase: {stderr}"
    );
}

#[test]
fn cli_exit_2_on_unknown_toolchain() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(
        td.path().join(".pithos"),
        "toolchains:\n  python: \"3.12\"\n",
    )
    .unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(2);

    // Assert
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("python"),
        "stderr missing offending toolchain name 'python': {stderr}"
    );
    assert!(
        stderr.contains("dotnet") && stderr.contains("rust") && stderr.contains("go"),
        "stderr missing valid toolchain names: {stderr}"
    );
}

#[test]
fn cli_exit_2_on_floating_version() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(
        td.path().join(".pithos"),
        "toolchains:\n  rust: \"stable\"\n",
    )
    .unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(2);

    // Assert
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("stable"),
        "stderr missing offending value 'stable': {stderr}"
    );
}

#[test]
fn cli_exit_2_on_invalid_apt_name() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(
        td.path().join(".pithos"),
        "toolchains: {}\nextras:\n  apt: [Git]\n",
    )
    .unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(2);

    // Assert
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("Git"),
        "stderr missing offending entry 'Git': {stderr}"
    );
}

#[test]
fn cli_exit_2_on_unknown_top_level_key() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), "toolchains: {}\nbogus: 1\n").unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(2);

    // Assert
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("bogus"),
        "stderr missing offending key 'bogus': {stderr}"
    );
    assert!(
        stderr.contains("toolchains"),
        "stderr missing valid-key 'toolchains': {stderr}"
    );
}

#[test]
fn cli_writes_dockerfile_to_pithos_d() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), VALID).unwrap();

    // Act
    Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(0);

    // Assert
    let dockerfile = td.path().join(".pithos.d").join("Dockerfile");
    assert!(
        dockerfile.exists(),
        "expected .pithos.d/Dockerfile to exist at {}",
        dockerfile.display()
    );
    let content = fs::read_to_string(&dockerfile).unwrap();
    assert_eq!(content, EXPECTED_DOCKERFILE);
}

#[test]
fn cli_overwrites_existing_dockerfile() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), VALID).unwrap();
    let dir = td.path().join(".pithos.d");
    fs::create_dir_all(&dir).unwrap();
    let dockerfile = dir.join("Dockerfile");
    fs::write(&dockerfile, "STALE\n").unwrap();

    // Act
    Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(0);

    // Assert
    let content = fs::read_to_string(&dockerfile).unwrap();
    assert_eq!(content, EXPECTED_DOCKERFILE);
}

#[test]
fn cli_skips_dockerfile_on_config_error() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), MALFORMED).unwrap();

    // Act
    Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(2);

    // Assert
    let dockerfile = td.path().join(".pithos.d").join("Dockerfile");
    assert!(
        !dockerfile.exists(),
        "expected .pithos.d/Dockerfile to NOT exist on config error, but found it at {}",
        dockerfile.display()
    );
}

#[test]
fn cli_emits_deterministic_dockerfile_for_identical_config() {
    // Guards future config-derived output; at 3.2 scope the bytes are static, so this is scaffolding for 3.3+.
    // Arrange
    let td_a = tempdir().unwrap();
    let td_b = tempdir().unwrap();
    fs::write(td_a.path().join(".pithos"), VALID).unwrap();
    fs::write(td_b.path().join(".pithos"), VALID).unwrap();

    // Act
    Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td_a)
        .assert()
        .code(0);
    Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td_b)
        .assert()
        .code(0);

    // Assert
    let bytes_a = fs::read(td_a.path().join(".pithos.d").join("Dockerfile")).unwrap();
    let bytes_b = fs::read(td_b.path().join(".pithos.d").join("Dockerfile")).unwrap();
    assert_eq!(
        bytes_a, bytes_b,
        "dockerfile not byte-identical across runs"
    );
}

#[test]
fn cli_emits_toolchain_layers_in_alphabetical_order() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(
        td.path().join(".pithos"),
        "toolchains:\n  rust: \"1.85.0\"\n  dotnet: \"10.0.102\"\n",
    )
    .unwrap();

    // Act
    Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(0);

    // Assert
    let dockerfile = td.path().join(".pithos.d").join("Dockerfile");
    let content = fs::read_to_string(&dockerfile).unwrap();
    let expected = "\
# Generated by pithos — do not edit
# Base stage: Debian bookworm-slim with Node, Python, uv, Pi CLI, and common dev tools pre-installed.
FROM ghcr.io/anton-kochev/pithos:base AS base
USER root

# Toolchain: installed via repo-local script, version pinned from .pithos. Alphabetical order keeps layer cache stable across re-renders.
COPY toolchains/dotnet-install.sh /usr/local/bin/dotnet-install.sh
RUN /usr/local/bin/dotnet-install.sh 10.0.102

COPY toolchains/rust-install.sh /usr/local/bin/rust-install.sh
RUN /usr/local/bin/rust-install.sh 1.85.0

# Pi-config defaults baked into /opt/pi-defaults/; entrypoint seeds them into the user's volume on first run. Tini handles PID 1 signal forwarding.
COPY pi-config/ /opt/pi-defaults/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
USER pi
ENTRYPOINT [\"/usr/bin/tini\", \"--\", \"/usr/local/bin/entrypoint.sh\"]
CMD [\"pi\"]
";
    assert_eq!(content, expected);
}

#[test]
fn cli_emits_extras_layer_after_toolchains() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(
        td.path().join(".pithos"),
        "toolchains:\n  dotnet: \"10.0.102\"\nextras:\n  apt: [git, libssl3]\n",
    )
    .unwrap();

    // Act
    Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(0);

    // Assert
    let dockerfile = td.path().join(".pithos.d").join("Dockerfile");
    let content = fs::read_to_string(&dockerfile).unwrap();
    let expected = "\
# Generated by pithos — do not edit
# Base stage: Debian bookworm-slim with Node, Python, uv, Pi CLI, and common dev tools pre-installed.
FROM ghcr.io/anton-kochev/pithos:base AS base
USER root

# Toolchain: installed via repo-local script, version pinned from .pithos. Alphabetical order keeps layer cache stable across re-renders.
COPY toolchains/dotnet-install.sh /usr/local/bin/dotnet-install.sh
RUN /usr/local/bin/dotnet-install.sh 10.0.102

# Extras: apt packages from .pithos. Installed after toolchains so editing the package list does not invalidate toolchain layers.
RUN apt-get update && apt-get install -y --no-install-recommends git libssl3 && rm -rf /var/lib/apt/lists/*

# Pi-config defaults baked into /opt/pi-defaults/; entrypoint seeds them into the user's volume on first run. Tini handles PID 1 signal forwarding.
COPY pi-config/ /opt/pi-defaults/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
USER pi
ENTRYPOINT [\"/usr/bin/tini\", \"--\", \"/usr/local/bin/entrypoint.sh\"]
CMD [\"pi\"]
";
    assert_eq!(content, expected);
}

#[test]
fn cli_build_subcommand_exits_nonzero_when_docker_unavailable() {
    // Arrange — minimal valid .pithos; the build branch will reach the docker
    // shellout, which fails at spawn because PATH is empty.
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), VALID).unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .arg("build")
        .current_dir(&td)
        .env_clear()
        .env("PATH", "")
        .env("HOME", std::env::var_os("HOME").unwrap_or_default())
        .env("TMPDIR", std::env::var_os("TMPDIR").unwrap_or_default())
        // Belt-and-suspenders: even if `docker` ends up on PATH after a
        // future refactor, point it at a non-existent socket so it can't
        // reach a real daemon.
        .env("DOCKER_HOST", "unix:///nonexistent/pithos-test.sock")
        .assert()
        .code(1);

    // Assert
    let output = assert.get_output();
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains(">> ERROR:"),
        "stderr missing '>> ERROR:' marker: {stderr}"
    );
    // Sanity: the Dockerfile should still have been emitted before the build
    // attempt — emit precedes the docker shellout in main.rs.
    assert!(
        td.path().join(".pithos.d").join("Dockerfile").is_file(),
        "Dockerfile should be emitted before the docker shellout failure"
    );
}

#[test]
fn cli_run_subcommand_exits_nonzero_when_docker_unavailable() {
    // Arrange — minimal valid .pithos; the run branch will reach the docker
    // shellout via ensure_image, which fails at spawn because PATH is empty.
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), VALID).unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .arg("run")
        .current_dir(&td)
        .env_clear()
        .env("PATH", "")
        .env("HOME", std::env::var_os("HOME").unwrap_or_default())
        .env("TMPDIR", std::env::var_os("TMPDIR").unwrap_or_default())
        .env("DOCKER_HOST", "unix:///nonexistent/pithos-test.sock")
        .assert()
        .code(1);

    // Assert
    let output = assert.get_output();
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains(">> ERROR:"),
        "stderr missing '>> ERROR:' marker: {stderr}"
    );
    assert!(
        td.path().join(".pithos.d").join("Dockerfile").is_file(),
        "Dockerfile should be emitted before the docker shellout failure"
    );
}

#[test]
fn cli_build_rejects_unknown_flag_writes_only_to_stderr() {
    // T-505 lock-down: narration goes to stderr; stdout stays clean so it's
    // safe to redirect stdout to /dev/null without losing error messaging.
    let td = tempdir().unwrap();
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .args(["build", "--nope"])
        .current_dir(&td)
        .assert()
        .code(1);
    let output = assert.get_output();
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains(">>"), "stderr missing '>>' marker: {stderr}");
    assert!(
        output.stdout.is_empty(),
        "stdout must be empty for T-505: {:?}",
        String::from_utf8_lossy(&output.stdout)
    );
}

#[test]
fn cli_build_rejects_unknown_flag() {
    // Arrange — no .pithos needed; unknown-flag parsing errors before any I/O.
    let td = tempdir().unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .args(["build", "--nope"])
        .current_dir(&td)
        .assert()
        .code(1);

    // Assert
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains(">> ERROR: unknown flag: --nope"),
        "stderr missing '>> ERROR: unknown flag: --nope' marker: {stderr}"
    );
    // Sanity: the fail-fast guard runs before any filesystem mutation.
    assert!(
        !td.path().join(".pithos.d").exists(),
        ".pithos.d should not be created when flag parsing fails"
    );
}
