use std::fs;

use assert_cmd::Command;
use tempfile::tempdir;

const MALFORMED: &str = "toolchains:\n  dotnet: \"10.0\"\nextras: [unclosed\n";
const VALID: &str = "toolchains: {}\n";
const EXPECTED_DOCKERFILE: &str = "\
# Generated by pithos — do not edit
# Base stage: Debian bookworm-slim with Node, Python, uv, Pi CLI, and common dev tools pre-installed.
FROM ghcr.io/anton-kochev/pithos:base AS base
USER root

# Pi-config defaults baked into /opt/pi-defaults/; entrypoint seeds them into the user's volume on first run. Tini handles PID 1 signal forwarding.
COPY pi-config/ /opt/pi-defaults/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
USER pi
ENTRYPOINT [\"/usr/bin/tini\", \"--\", \"/usr/local/bin/entrypoint.sh\"]
CMD [\"pi\"]
";

#[test]
fn cli_exit_2_on_parse_error() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), MALFORMED).unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(2);

    // Assert
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("line "),
        "stderr missing 'line N' phrase: {stderr}"
    );
}

#[test]
fn cli_reads_from_cwd() {
    // Launcher reads from cwd: valid config → emits Dockerfile, malformed
    // config → parse error (exit 2) and no emit.
    // Arrange
    let good = tempdir().unwrap();
    let bad = tempdir().unwrap();
    fs::write(good.path().join(".pithos"), VALID).unwrap();
    fs::write(bad.path().join(".pithos"), MALFORMED).unwrap();

    // Act — good path: exit code is incidental (daemon probe), Dockerfile
    // emission is the invariant that proves the valid config was read.
    let _ = Command::cargo_bin("pithos")
        .unwrap()
        .arg("build")
        .current_dir(&good)
        .env_clear()
        .env("PATH", "")
        .env("HOME", std::env::var_os("HOME").unwrap_or_default())
        .env("TMPDIR", std::env::var_os("TMPDIR").unwrap_or_default())
        .env("DOCKER_HOST", "unix:///nonexistent/pithos-test.sock")
        .assert();
    let bad_code = Command::cargo_bin("pithos")
        .unwrap()
        .arg("build")
        .current_dir(&bad)
        .env_clear()
        .env("PATH", "")
        .env("HOME", std::env::var_os("HOME").unwrap_or_default())
        .env("TMPDIR", std::env::var_os("TMPDIR").unwrap_or_default())
        .env("DOCKER_HOST", "unix:///nonexistent/pithos-test.sock")
        .assert()
        .code(2)
        .get_output()
        .status
        .code();

    // Assert
    assert!(
        good.path().join(".pithos.d").join("Dockerfile").exists(),
        "valid config should have emitted .pithos.d/Dockerfile"
    );
    assert_eq!(bad_code, Some(2), "malformed config should exit 2");
    assert!(
        !bad.path().join(".pithos.d").join("Dockerfile").exists(),
        "malformed config should NOT emit Dockerfile (parse fails before emit)"
    );
}

#[test]
fn cli_exit_2_when_pithos_missing_with_minimal_example_hint() {
    // Arrange
    let td = tempdir().unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(2);

    // Assert
    let output = assert.get_output();
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains(".pithos not found"),
        "stderr missing '.pithos not found' phrase: {stderr}"
    );
    assert!(
        stderr.contains("toolchains: {}"),
        "stderr missing 'toolchains: {{}}' minimal example: {stderr}"
    );
    assert!(
        output.stdout.is_empty(),
        "stdout should be empty, got: {:?}",
        String::from_utf8_lossy(&output.stdout)
    );
}

#[test]
fn cli_exit_2_on_missing_toolchains() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), "{}\n").unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(2);

    // Assert
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("missing required key"),
        "stderr missing 'missing required key' phrase: {stderr}"
    );
    assert!(
        stderr.contains("toolchains"),
        "stderr missing 'toolchains' phrase: {stderr}"
    );
}

#[test]
fn cli_exit_2_on_unknown_toolchain() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(
        td.path().join(".pithos"),
        "toolchains:\n  python: \"3.12\"\n",
    )
    .unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(2);

    // Assert
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("python"),
        "stderr missing offending toolchain name 'python': {stderr}"
    );
    assert!(
        stderr.contains("dotnet") && stderr.contains("rust") && stderr.contains("go"),
        "stderr missing valid toolchain names: {stderr}"
    );
}

#[test]
fn cli_exit_2_on_floating_version() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(
        td.path().join(".pithos"),
        "toolchains:\n  rust: \"stable\"\n",
    )
    .unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(2);

    // Assert
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("stable"),
        "stderr missing offending value 'stable': {stderr}"
    );
}

#[test]
fn cli_exit_2_on_invalid_apt_name() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(
        td.path().join(".pithos"),
        "toolchains: {}\nextras:\n  apt: [Git]\n",
    )
    .unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(2);

    // Assert
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("Git"),
        "stderr missing offending entry 'Git': {stderr}"
    );
}

#[test]
fn cli_exit_2_on_unknown_top_level_key() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), "toolchains: {}\nbogus: 1\n").unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(2);

    // Assert
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("bogus"),
        "stderr missing offending key 'bogus': {stderr}"
    );
    assert!(
        stderr.contains("toolchains"),
        "stderr missing valid-key 'toolchains': {stderr}"
    );
}

#[test]
fn cli_writes_dockerfile_to_pithos_d() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), VALID).unwrap();

    // Act — exit code is incidental (daemon probe failure); Dockerfile
    // content is the invariant under test.
    let _ = Command::cargo_bin("pithos")
        .unwrap()
        .arg("build")
        .current_dir(&td)
        .env_clear()
        .env("PATH", "")
        .env("HOME", std::env::var_os("HOME").unwrap_or_default())
        .env("TMPDIR", std::env::var_os("TMPDIR").unwrap_or_default())
        .env("DOCKER_HOST", "unix:///nonexistent/pithos-test.sock")
        .assert();

    // Assert — emit precedes daemon probe, so Dockerfile still gets written.
    let dockerfile = td.path().join(".pithos.d").join("Dockerfile");
    assert!(
        dockerfile.exists(),
        "expected .pithos.d/Dockerfile to exist at {}",
        dockerfile.display()
    );
    let content = fs::read_to_string(&dockerfile).unwrap();
    assert_eq!(content, EXPECTED_DOCKERFILE);
}

#[test]
fn cli_overwrites_existing_dockerfile() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), VALID).unwrap();
    let dir = td.path().join(".pithos.d");
    fs::create_dir_all(&dir).unwrap();
    let dockerfile = dir.join("Dockerfile");
    fs::write(&dockerfile, "STALE\n").unwrap();

    // Act — exit code is incidental (daemon probe failure); Dockerfile
    // content is the invariant under test.
    let _ = Command::cargo_bin("pithos")
        .unwrap()
        .arg("build")
        .current_dir(&td)
        .env_clear()
        .env("PATH", "")
        .env("HOME", std::env::var_os("HOME").unwrap_or_default())
        .env("TMPDIR", std::env::var_os("TMPDIR").unwrap_or_default())
        .env("DOCKER_HOST", "unix:///nonexistent/pithos-test.sock")
        .assert();

    // Assert
    let content = fs::read_to_string(&dockerfile).unwrap();
    assert_eq!(content, EXPECTED_DOCKERFILE);
}

#[test]
fn cli_skips_dockerfile_on_config_error() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), MALFORMED).unwrap();

    // Act
    Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .assert()
        .code(2);

    // Assert
    let dockerfile = td.path().join(".pithos.d").join("Dockerfile");
    assert!(
        !dockerfile.exists(),
        "expected .pithos.d/Dockerfile to NOT exist on config error, but found it at {}",
        dockerfile.display()
    );
}

#[test]
fn cli_emits_deterministic_dockerfile_for_identical_config() {
    // Guards future config-derived output; at 3.2 scope the bytes are static, so this is scaffolding for 3.3+.
    // Arrange
    let td_a = tempdir().unwrap();
    let td_b = tempdir().unwrap();
    fs::write(td_a.path().join(".pithos"), VALID).unwrap();
    fs::write(td_b.path().join(".pithos"), VALID).unwrap();

    // Act — exit code is incidental (daemon probe failure); Dockerfile
    // content is the invariant under test.
    let _ = Command::cargo_bin("pithos")
        .unwrap()
        .arg("build")
        .current_dir(&td_a)
        .env_clear()
        .env("PATH", "")
        .env("HOME", std::env::var_os("HOME").unwrap_or_default())
        .env("TMPDIR", std::env::var_os("TMPDIR").unwrap_or_default())
        .env("DOCKER_HOST", "unix:///nonexistent/pithos-test.sock")
        .assert();
    let _ = Command::cargo_bin("pithos")
        .unwrap()
        .arg("build")
        .current_dir(&td_b)
        .env_clear()
        .env("PATH", "")
        .env("HOME", std::env::var_os("HOME").unwrap_or_default())
        .env("TMPDIR", std::env::var_os("TMPDIR").unwrap_or_default())
        .env("DOCKER_HOST", "unix:///nonexistent/pithos-test.sock")
        .assert();

    // Assert
    let bytes_a = fs::read(td_a.path().join(".pithos.d").join("Dockerfile")).unwrap();
    let bytes_b = fs::read(td_b.path().join(".pithos.d").join("Dockerfile")).unwrap();
    assert_eq!(
        bytes_a, bytes_b,
        "dockerfile not byte-identical across runs"
    );
}

#[test]
fn cli_emits_toolchain_layers_in_alphabetical_order() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(
        td.path().join(".pithos"),
        "toolchains:\n  rust: \"1.85.0\"\n  dotnet: \"10.0.102\"\n",
    )
    .unwrap();

    // Act — exit code is incidental (daemon probe failure); Dockerfile
    // content is the invariant under test.
    let _ = Command::cargo_bin("pithos")
        .unwrap()
        .arg("build")
        .current_dir(&td)
        .env_clear()
        .env("PATH", "")
        .env("HOME", std::env::var_os("HOME").unwrap_or_default())
        .env("TMPDIR", std::env::var_os("TMPDIR").unwrap_or_default())
        .env("DOCKER_HOST", "unix:///nonexistent/pithos-test.sock")
        .assert();

    // Assert
    let dockerfile = td.path().join(".pithos.d").join("Dockerfile");
    let content = fs::read_to_string(&dockerfile).unwrap();
    let expected = "\
# Generated by pithos — do not edit
# Base stage: Debian bookworm-slim with Node, Python, uv, Pi CLI, and common dev tools pre-installed.
FROM ghcr.io/anton-kochev/pithos:base AS base
USER root

# Toolchain: installed via repo-local script, version pinned from .pithos. Alphabetical order keeps layer cache stable across re-renders.
COPY toolchains/dotnet-install.sh /usr/local/bin/dotnet-install.sh
RUN /usr/local/bin/dotnet-install.sh 10.0.102

COPY toolchains/rust-install.sh /usr/local/bin/rust-install.sh
RUN /usr/local/bin/rust-install.sh 1.85.0

# Pi-config defaults baked into /opt/pi-defaults/; entrypoint seeds them into the user's volume on first run. Tini handles PID 1 signal forwarding.
COPY pi-config/ /opt/pi-defaults/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
USER pi
ENTRYPOINT [\"/usr/bin/tini\", \"--\", \"/usr/local/bin/entrypoint.sh\"]
CMD [\"pi\"]
";
    assert_eq!(content, expected);
}

#[test]
fn cli_emits_extras_layer_after_toolchains() {
    // Arrange
    let td = tempdir().unwrap();
    fs::write(
        td.path().join(".pithos"),
        "toolchains:\n  dotnet: \"10.0.102\"\nextras:\n  apt: [git, libssl3]\n",
    )
    .unwrap();

    // Act — exit code is incidental (daemon probe failure); Dockerfile
    // content is the invariant under test.
    let _ = Command::cargo_bin("pithos")
        .unwrap()
        .arg("build")
        .current_dir(&td)
        .env_clear()
        .env("PATH", "")
        .env("HOME", std::env::var_os("HOME").unwrap_or_default())
        .env("TMPDIR", std::env::var_os("TMPDIR").unwrap_or_default())
        .env("DOCKER_HOST", "unix:///nonexistent/pithos-test.sock")
        .assert();

    // Assert
    let dockerfile = td.path().join(".pithos.d").join("Dockerfile");
    let content = fs::read_to_string(&dockerfile).unwrap();
    let expected = "\
# Generated by pithos — do not edit
# Base stage: Debian bookworm-slim with Node, Python, uv, Pi CLI, and common dev tools pre-installed.
FROM ghcr.io/anton-kochev/pithos:base AS base
USER root

# Toolchain: installed via repo-local script, version pinned from .pithos. Alphabetical order keeps layer cache stable across re-renders.
COPY toolchains/dotnet-install.sh /usr/local/bin/dotnet-install.sh
RUN /usr/local/bin/dotnet-install.sh 10.0.102

# Extras: apt packages from .pithos. Installed after toolchains so editing the package list does not invalidate toolchain layers.
RUN apt-get update && apt-get install -y --no-install-recommends git libssl3 && rm -rf /var/lib/apt/lists/*

# Pi-config defaults baked into /opt/pi-defaults/; entrypoint seeds them into the user's volume on first run. Tini handles PID 1 signal forwarding.
COPY pi-config/ /opt/pi-defaults/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
USER pi
ENTRYPOINT [\"/usr/bin/tini\", \"--\", \"/usr/local/bin/entrypoint.sh\"]
CMD [\"pi\"]
";
    assert_eq!(content, expected);
}

#[test]
fn cli_build_subcommand_exits_nonzero_when_docker_unavailable() {
    // Arrange — minimal valid .pithos; the build branch will reach the docker
    // shellout, which fails at spawn because PATH is empty.
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), VALID).unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .arg("build")
        .current_dir(&td)
        .env_clear()
        .env("PATH", "")
        .env("HOME", std::env::var_os("HOME").unwrap_or_default())
        .env("TMPDIR", std::env::var_os("TMPDIR").unwrap_or_default())
        // Belt-and-suspenders: even if `docker` ends up on PATH after a
        // future refactor, point it at a non-existent socket so it can't
        // reach a real daemon.
        .env("DOCKER_HOST", "unix:///nonexistent/pithos-test.sock")
        .assert()
        .code(1);

    // Assert
    let output = assert.get_output();
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("» ERROR:"),
        "stderr missing '» ERROR:' marker: {stderr}"
    );
    // Sanity: the Dockerfile should still have been emitted before the build
    // attempt — emit precedes the docker shellout in main.rs.
    assert!(
        td.path().join(".pithos.d").join("Dockerfile").is_file(),
        "Dockerfile should be emitted before the docker shellout failure"
    );
}

#[test]
fn cli_run_subcommand_exits_nonzero_when_docker_unavailable() {
    // Arrange — minimal valid .pithos; the run branch will reach the docker
    // shellout via ensure_image, which fails at spawn because PATH is empty.
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), VALID).unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .arg("run")
        .current_dir(&td)
        .env_clear()
        .env("PATH", "")
        .env("HOME", std::env::var_os("HOME").unwrap_or_default())
        .env("TMPDIR", std::env::var_os("TMPDIR").unwrap_or_default())
        .env("DOCKER_HOST", "unix:///nonexistent/pithos-test.sock")
        .assert()
        .code(1);

    // Assert
    let output = assert.get_output();
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("» ERROR:"),
        "stderr missing '» ERROR:' marker: {stderr}"
    );
    assert!(
        td.path().join(".pithos.d").join("Dockerfile").is_file(),
        "Dockerfile should be emitted before the docker shellout failure"
    );
}

#[test]
fn cli_run_subcommand_with_cmd_reaches_docker_shellout() {
    // Arrange — mirror the no-docker run test but invoke with `-- bash` to
    // prove the cmd-parsing branch threads through rather than being rejected
    // upstream. A parse-phase rejection of `--` would narrate "unknown flag:"
    // or "unknown subcommand:"; if neither appears AND the Dockerfile was
    // emitted, the cmd branch made it past parse into the execution pipeline.
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), VALID).unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .args(["run", "--", "bash"])
        .current_dir(&td)
        .env_clear()
        .env("PATH", "")
        .env("HOME", std::env::var_os("HOME").unwrap_or_default())
        .env("TMPDIR", std::env::var_os("TMPDIR").unwrap_or_default())
        .env("DOCKER_HOST", "unix:///nonexistent/pithos-test.sock")
        .assert()
        .code(1);

    // Assert — absence of parse-phase markers proves `-- bash` was accepted
    // as cmd; Dockerfile emission proves execution reached post-parse I/O.
    let output = assert.get_output();
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("» ERROR:"),
        "stderr missing '» ERROR:' marker: {stderr}"
    );
    assert!(
        !stderr.contains("unknown flag:"),
        "cmd branch was rejected as unknown flag: {stderr}"
    );
    assert!(
        !stderr.contains("unknown subcommand:"),
        "cmd branch was rejected as unknown subcommand: {stderr}"
    );
    assert!(
        td.path().join(".pithos.d").join("Dockerfile").is_file(),
        "Dockerfile should be emitted before the docker shellout failure"
    );
}

#[test]
fn cli_build_rejects_unknown_flag_writes_only_to_stderr() {
    // T-505 lock-down: narration goes to stderr; stdout stays clean so it's
    // safe to redirect stdout to /dev/null without losing error messaging.
    let td = tempdir().unwrap();
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .args(["build", "--nope"])
        .current_dir(&td)
        .assert()
        .code(2);
    let output = assert.get_output();
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("»"), "stderr missing '»' marker: {stderr}");
    assert!(
        output.stdout.is_empty(),
        "stdout must be empty for T-505: {:?}",
        String::from_utf8_lossy(&output.stdout)
    );
}

#[test]
fn cli_bare_invocation_dispatches_run() {
    // Bare `pithos` no longer short-circuits with exit 0; Dockerfile gets
    // emitted. Unit test `from_args_no_subcommand_defaults_to_run` locks the
    // Run-specific parse contract; this integration test only proves the
    // post-parse pipeline engages.
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), VALID).unwrap();
    let _ = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(&td)
        .env_clear()
        .env("PATH", "")
        .env("HOME", std::env::var_os("HOME").unwrap_or_default())
        .env("TMPDIR", std::env::var_os("TMPDIR").unwrap_or_default())
        .env("DOCKER_HOST", "unix:///nonexistent/pithos-test.sock")
        .assert();
    assert!(
        td.path().join(".pithos.d/Dockerfile").exists(),
        "Dockerfile should be emitted before daemon probe on bare invocation"
    );
}

#[test]
fn cli_exit_126_within_3s_when_daemon_unreachable() {
    // NFR-12 / T-504: unreachable daemon → exit 126 within 3s with guidance
    // to start Docker Desktop.
    //
    // Gate on `docker --version` (not `which docker`): --version proves the
    // binary exists AND execs cleanly, so the failure lands in Unreachable
    // (daemon-side), not Spawn (binary-missing). Without the gate, a CI
    // runner without docker would produce a false green via the Spawn path.
    let docker_ok = std::process::Command::new("docker")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false);
    if !docker_ok {
        eprintln!(
            "cli_exit_126_within_3s_when_daemon_unreachable: skipped (docker not on PATH)"
        );
        return;
    }

    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), VALID).unwrap();

    let start = std::time::Instant::now();
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .arg("build")
        .current_dir(&td)
        .env("DOCKER_HOST", "unix:///nonexistent-pithos-6.5.sock")
        .assert()
        .code(126);
    let elapsed = start.elapsed();

    // 7s budget = 3s probe cap + 4s slack for cold-macOS CI (CLI-plugin scan
    // + child spawn/teardown add ~300-500ms).
    assert!(
        elapsed < std::time::Duration::from_secs(7),
        "probe exceeded 3s + slack: {elapsed:?}"
    );

    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("» ERROR:"),
        "stderr missing '» ERROR:' marker: {stderr}"
    );
    assert!(
        stderr.contains("start Docker Desktop"),
        "stderr missing 'start Docker Desktop' guidance: {stderr}"
    );
    // Parse-phase regression guard: a future refactor that makes
    // `pithos build` fail at parse instead of probe would surface
    // different exit codes; these catch the miscategorization even if
    // the primary 126 assertion happened to pass spuriously.
    assert!(
        !stderr.contains("unknown flag:"),
        "unexpected parse-phase rejection: {stderr}"
    );
    assert!(
        !stderr.contains("unknown subcommand:"),
        "unexpected parse-phase rejection: {stderr}"
    );
}

#[test]
fn cli_build_rejects_unknown_flag() {
    // Arrange — no .pithos needed; unknown-flag parsing errors before any I/O.
    let td = tempdir().unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .args(["build", "--nope"])
        .current_dir(&td)
        .assert()
        .code(2);

    // Assert
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("» ERROR: unknown flag: --nope"),
        "stderr missing '» ERROR: unknown flag: --nope' marker: {stderr}"
    );
    assert!(
        stderr.contains("usage:"),
        "stderr missing 'usage:' line after reject: {stderr}"
    );
    // Sanity: the fail-fast guard runs before any filesystem mutation.
    assert!(
        !td.path().join(".pithos.d").exists(),
        ".pithos.d should not be created when flag parsing fails"
    );
}

#[test]
fn cli_help_exits_0_and_lists_subcommands() {
    let td = tempdir().unwrap();

    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .arg("help")
        .current_dir(&td)
        .assert()
        .code(0);

    let output = assert.get_output();
    let stdout = String::from_utf8_lossy(&output.stdout);
    for name in ["run", "build", "info", "clean", "help", "version"] {
        assert!(
            stdout.contains(name),
            "stdout missing subcommand {name:?}: {stdout}"
        );
    }
    assert!(
        output.stderr.is_empty(),
        "stderr must be empty on help: {:?}",
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
fn cli_version_exits_0_and_prints_version() {
    let td = tempdir().unwrap();

    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .arg("version")
        .current_dir(&td)
        .assert()
        .code(0);

    let output = assert.get_output();
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        stdout.starts_with("pithos "),
        "stdout should start with 'pithos ': {stdout}"
    );
    assert!(
        stdout.contains(env!("CARGO_PKG_VERSION")),
        "stdout missing CARGO_PKG_VERSION ({}): {stdout}",
        env!("CARGO_PKG_VERSION")
    );
    assert!(
        output.stderr.is_empty(),
        "stderr must be empty on version: {:?}",
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
fn cli_help_does_not_touch_filesystem() {
    // No `.pithos` present; `help` must short-circuit before `read_pithos`
    // and before any `.pithos.d/` creation.
    let td = tempdir().unwrap();

    Command::cargo_bin("pithos")
        .unwrap()
        .arg("help")
        .current_dir(&td)
        .assert()
        .code(0);

    assert!(
        !td.path().join(".pithos.d").exists(),
        ".pithos.d should not be created by `pithos help`"
    );
}

#[test]
fn cli_version_does_not_touch_filesystem() {
    let td = tempdir().unwrap();

    Command::cargo_bin("pithos")
        .unwrap()
        .arg("version")
        .current_dir(&td)
        .assert()
        .code(0);

    assert!(
        !td.path().join(".pithos.d").exists(),
        ".pithos.d should not be created by `pithos version`"
    );
}

#[test]
fn cli_help_rejects_trailing_arg() {
    let td = tempdir().unwrap();

    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .args(["help", "extra"])
        .current_dir(&td)
        .assert()
        .code(2);

    let output = assert.get_output();
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("unknown flag: extra"),
        "stderr missing 'unknown flag: extra': {stderr}"
    );
    assert!(
        stderr.contains("usage:"),
        "stderr missing 'usage:' line after reject: {stderr}"
    );
    assert!(
        output.stdout.is_empty(),
        "stdout must be empty on reject: {:?}",
        String::from_utf8_lossy(&output.stdout)
    );
}

#[test]
fn cli_unknown_subcommand_exits_2_with_usage() {
    // Arrange
    let td = tempdir().unwrap();

    // Act
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .arg("bogus")
        .current_dir(&td)
        .assert()
        .code(2);

    // Assert
    let output = assert.get_output();
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("unknown subcommand: bogus"),
        "stderr missing error: {stderr}"
    );
    assert!(
        stderr.contains("usage:"),
        "stderr missing usage line: {stderr}"
    );
    // T-505 invariant: narration goes to stderr; stdout stays clean.
    assert!(
        output.stdout.is_empty(),
        "stdout must be empty for T-505: {:?}",
        String::from_utf8_lossy(&output.stdout)
    );
    // Fail-fast guard: parse error runs before any filesystem mutation.
    assert!(
        !td.path().join(".pithos.d").exists(),
        ".pithos.d should not be created when subcommand parsing fails"
    );
}

#[test]
fn cli_info_exit_2_when_pithos_missing() {
    let td = tempdir().unwrap();
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .arg("info")
        .current_dir(&td)
        .assert()
        .code(2);
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains(".pithos not found"),
        "stderr missing '.pithos not found' phrase: {stderr}"
    );
}

#[test]
fn cli_info_exit_2_on_parse_error() {
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), MALFORMED).unwrap();
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .arg("info")
        .current_dir(&td)
        .assert()
        .code(2);
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("line "),
        "stderr missing 'line N' phrase: {stderr}"
    );
}

#[test]
fn cli_info_rejects_trailing_arg() {
    let td = tempdir().unwrap();
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .args(["info", "extra"])
        .current_dir(&td)
        .assert()
        .code(2);
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("unknown flag: extra"),
        "stderr missing 'unknown flag: extra': {stderr}"
    );
}

#[test]
fn cli_info_does_not_create_pithos_d() {
    let td = tempdir().unwrap();
    fs::write(td.path().join(".pithos"), VALID).unwrap();
    let _ = Command::cargo_bin("pithos")
        .unwrap()
        .arg("info")
        .current_dir(&td)
        .env_clear()
        .env("PATH", "")
        .env("HOME", std::env::var_os("HOME").unwrap_or_default())
        .env("TMPDIR", std::env::var_os("TMPDIR").unwrap_or_default())
        .env("DOCKER_HOST", "unix:///nonexistent/pithos-test.sock")
        .assert();
    assert!(
        !td.path().join(".pithos.d").exists(),
        "`pithos info` should not create .pithos.d/"
    );
}

#[test]
fn cli_clean_rejects_unknown_flag() {
    let td = tempfile::tempdir().unwrap();
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(td.path())
        .args(["clean", "--nope"])
        .assert()
        .failure()
        .code(2);
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("unknown flag"),
        "stderr missing 'unknown flag': {stderr}"
    );
}

#[test]
fn cli_clean_rejects_trailing_arg() {
    let td = tempfile::tempdir().unwrap();
    Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(td.path())
        .args(["clean", "--all", "extra"])
        .assert()
        .failure()
        .code(2);
}

#[test]
fn cli_clean_does_not_require_pithos() {
    // Empty tempdir, no docker on PATH, no DOCKER_HOST. With Clean
    // short-circuiting before the .pithos read, we hit require_daemon's
    // Spawn path, which classify_probe maps to exit 1 — NOT exit 2 (which
    // would mean we accidentally hit the .pithos-required path).
    let td = tempfile::tempdir().unwrap();
    let assertion = Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(td.path())
        .env_clear()
        .env("PATH", "")
        .env("DOCKER_HOST", "/nonexistent/docker.sock")
        .arg("clean")
        .assert()
        .failure()
        .code(1);
    let stderr = String::from_utf8_lossy(&assertion.get_output().stderr).to_string();
    assert!(
        !stderr.contains(".pithos not found"),
        "clean should not require .pithos; got stderr: {stderr}"
    );
}

#[test]
fn cli_clean_all_does_not_require_pithos() {
    let td = tempfile::tempdir().unwrap();
    Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(td.path())
        .env_clear()
        .env("PATH", "")
        .env("DOCKER_HOST", "/nonexistent/docker.sock")
        .args(["clean", "--all"])
        .assert()
        .failure()
        .code(1);
}

#[test]
fn cli_clean_does_not_create_pithos_d() {
    let td = tempfile::tempdir().unwrap();
    Command::cargo_bin("pithos")
        .unwrap()
        .current_dir(td.path())
        .env_clear()
        .env("PATH", "")
        .env("DOCKER_HOST", "/nonexistent/docker.sock")
        .arg("clean")
        .assert()
        .failure();
    assert!(
        !td.path().join(".pithos.d").exists(),
        ".pithos.d/ should not be created by clean"
    );
}

#[test]
fn cli_creates_pithos_on_empty_input() {
    // User hits Enter at the [Y/n] prompt → yes-default → file written and
    // `pithos info` continues into a clean SUCCESS.
    //
    // We nest a non-dot subdir inside the tempdir because `tempdir()` produces
    // basenames starting with `.tmp...`, which `project::name_from_path`
    // rejects (dotfile-style names collide under sanitization), making `info`
    // exit 1 before reaching SUCCESS.
    let td = tempdir().unwrap();
    let proj = td.path().join("proj");
    fs::create_dir(&proj).unwrap();
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .arg("info")
        .current_dir(&proj)
        .write_stdin("\n")
        .assert()
        .code(0);
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("Created"),
        "stderr missing 'Created' narration: {stderr}"
    );
    let pithos_path = proj.join(".pithos");
    let content = fs::read_to_string(&pithos_path).expect(".pithos should have been created");
    assert_eq!(content, "toolchains: {}\n");
}

#[test]
fn cli_creates_pithos_on_y_input() {
    // Explicit `y` is also yes — locks the typed-accept branch independently
    // of the empty-input default in case the parser's default ever flips.
    let td = tempdir().unwrap();
    let proj = td.path().join("proj");
    fs::create_dir(&proj).unwrap();
    Command::cargo_bin("pithos")
        .unwrap()
        .arg("info")
        .current_dir(&proj)
        .write_stdin("y\n")
        .assert()
        .code(0);
    let pithos_path = proj.join(".pithos");
    let content = fs::read_to_string(&pithos_path).expect(".pithos should have been created");
    assert_eq!(content, "toolchains: {}\n");
}

#[test]
fn cli_does_not_create_pithos_on_n_input() {
    // `n` declines → no file, exit 2, narration confirms abort.
    let td = tempdir().unwrap();
    let proj = td.path().join("proj");
    fs::create_dir(&proj).unwrap();
    let assert = Command::cargo_bin("pithos")
        .unwrap()
        .arg("info")
        .current_dir(&proj)
        .write_stdin("n\n")
        .assert()
        .code(2);
    let stderr = String::from_utf8_lossy(&assert.get_output().stderr);
    assert!(
        stderr.contains("aborted"),
        "stderr missing 'aborted' narration: {stderr}"
    );
    assert!(
        !proj.join(".pithos").exists(),
        ".pithos should NOT exist after declining the prompt"
    );
}
