use std::collections::BTreeMap;
use std::fmt::Write as _;

use saphyr::YamlOwned;

const BASE: &str = "\
# Generated by pithos — do not edit
FROM ghcr.io/anton-kochev/pithos:base AS base
";

/// Emit a Dockerfile for the given parsed `.pithos` config.
///
/// **Precondition:** `yaml` must be the validated output of
/// [`crate::config::load`]. This function trusts that validation has
/// already confirmed the top-level `toolchains` mapping exists and all
/// name/version scalars are well-formed strings; it will panic otherwise.
pub fn emit(yaml: &YamlOwned) -> String {
    let mut out = String::with_capacity(BASE.len() + 128);
    out.push_str(BASE);
    for (name, version) in sorted_toolchains(yaml) {
        writeln!(out).unwrap();
        writeln!(
            out,
            "COPY toolchains/{name}-install.sh /usr/local/bin/{name}-install.sh"
        )
        .unwrap();
        writeln!(out, "RUN /usr/local/bin/{name}-install.sh {version}").unwrap();
    }
    out
}

fn sorted_toolchains(yaml: &YamlOwned) -> BTreeMap<String, String> {
    // BTreeMap yields sort-by-key for free — determinism is structural.
    // All .expect() calls document the validation contract.
    let mapping = yaml.as_mapping().expect("validated by config::load");
    let mut toolchains: Option<&YamlOwned> = None;
    for (key, value) in mapping {
        let name = key.as_str().expect("validated by config::load");
        if name == "toolchains" {
            toolchains = Some(value);
            break;
        }
    }
    let toolchains = toolchains.expect("validated by config::load");
    let toolchains_map = toolchains.as_mapping().expect("validated by config::load");
    toolchains_map
        .iter()
        .map(|(k, v)| {
            let name = k.as_str().expect("validated by config::load");
            let version = v.as_str().expect("validated by config::load");
            (name.to_string(), version.to_string())
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::emit;
    use crate::config;

    #[test]
    fn emit_base_only_for_empty_toolchains() {
        // Arrange
        const VALID: &str = "toolchains: {}\n";
        let yaml = config::load(VALID.as_bytes()).unwrap();

        // Act
        let output = emit(&yaml);

        // Assert
        let expected = "\
# Generated by pithos — do not edit
FROM ghcr.io/anton-kochev/pithos:base AS base
";
        assert_eq!(output, expected);
    }

    #[test]
    fn emit_single_toolchain_layer() {
        // Arrange
        const VALID: &str = "toolchains:\n  dotnet: \"10.0.102\"\n";
        let yaml = config::load(VALID.as_bytes()).unwrap();

        // Act
        let output = emit(&yaml);

        // Assert
        let expected = "\
# Generated by pithos — do not edit
FROM ghcr.io/anton-kochev/pithos:base AS base

COPY toolchains/dotnet-install.sh /usr/local/bin/dotnet-install.sh
RUN /usr/local/bin/dotnet-install.sh 10.0.102
";
        assert_eq!(output, expected);
    }

    #[test]
    fn emit_sorts_toolchains_alphabetically() {
        // Arrange
        const VALID: &str = "toolchains:\n  rust: \"1.85.0\"\n  dotnet: \"10.0.102\"\n";
        let yaml = config::load(VALID.as_bytes()).unwrap();

        // Act
        let output = emit(&yaml);

        // Assert
        let expected = "\
# Generated by pithos — do not edit
FROM ghcr.io/anton-kochev/pithos:base AS base

COPY toolchains/dotnet-install.sh /usr/local/bin/dotnet-install.sh
RUN /usr/local/bin/dotnet-install.sh 10.0.102

COPY toolchains/rust-install.sh /usr/local/bin/rust-install.sh
RUN /usr/local/bin/rust-install.sh 1.85.0
";
        assert_eq!(output, expected);
    }

    #[test]
    fn emit_all_three_toolchains_exact_match() {
        // Arrange
        const VALID: &str = "\
toolchains:
  dotnet: \"10.0.102\"
  go: \"1.22.0\"
  rust: \"1.85.0\"
";
        let yaml = config::load(VALID.as_bytes()).unwrap();

        // Act
        let output = emit(&yaml);

        // Assert
        let expected = "\
# Generated by pithos — do not edit
FROM ghcr.io/anton-kochev/pithos:base AS base

COPY toolchains/dotnet-install.sh /usr/local/bin/dotnet-install.sh
RUN /usr/local/bin/dotnet-install.sh 10.0.102

COPY toolchains/go-install.sh /usr/local/bin/go-install.sh
RUN /usr/local/bin/go-install.sh 1.22.0

COPY toolchains/rust-install.sh /usr/local/bin/rust-install.sh
RUN /usr/local/bin/rust-install.sh 1.85.0
";
        assert_eq!(output, expected);
    }

    #[test]
    fn emit_passes_version_verbatim() {
        // Arrange
        const VALID: &str = "toolchains:\n  dotnet: \"10.0.102\"\n";
        let yaml = config::load(VALID.as_bytes()).unwrap();

        // Act
        let output = emit(&yaml);

        // Assert
        assert_eq!(
            output.matches("10.0.102").count(),
            1,
            "version should appear exactly once on the RUN line"
        );
        assert!(
            output.contains("RUN /usr/local/bin/dotnet-install.sh 10.0.102\n"),
            "RUN line with verbatim version missing: {output}"
        );
    }
}
