use std::collections::BTreeMap;
use std::fmt::Write as _;

use saphyr::YamlOwned;

const BASE: &str = "\
# Generated by pithos — do not edit
# Base stage: Debian bookworm-slim with Node, Python, uv, Pi CLI, and common dev tools pre-installed.
FROM ghcr.io/anton-kochev/pithos:base AS base
USER root
";

/// Emit a Dockerfile for the given parsed `.pithos` config.
///
/// **Precondition:** `yaml` must be the validated output of
/// [`crate::config::load`]. This function trusts that validation has
/// already confirmed the top-level `toolchains` mapping exists and all
/// name/version scalars are well-formed strings; it will panic otherwise.
pub fn emit(yaml: &YamlOwned) -> String {
    let mut out = String::with_capacity(BASE.len() + 128);
    out.push_str(BASE);
    let toolchains = sorted_toolchains(yaml);
    if !toolchains.is_empty() {
        writeln!(out).unwrap();
        writeln!(
            out,
            "# Toolchain: installed via repo-local script, version pinned from .pithos. Alphabetical order keeps layer cache stable across re-renders."
        )
        .unwrap();
        for (i, (name, version)) in toolchains.iter().enumerate() {
            if i > 0 {
                writeln!(out).unwrap();
            }
            writeln!(
                out,
                "COPY toolchains/{name}-install.sh /usr/local/bin/{name}-install.sh"
            )
            .unwrap();
            writeln!(out, "RUN /usr/local/bin/{name}-install.sh {version}").unwrap();
        }
    }
    let packages = apt_packages(yaml);
    if !packages.is_empty() {
        writeln!(out).unwrap();
        writeln!(
            out,
            "# Extras: apt packages from .pithos. Installed after toolchains so editing the package list does not invalidate toolchain layers."
        )
        .unwrap();
        writeln!(
            out,
            "RUN apt-get update && apt-get install -y --no-install-recommends {} && rm -rf /var/lib/apt/lists/*",
            packages.join(" ")
        )
        .unwrap();
    }
    writeln!(out).unwrap();
    writeln!(
        out,
        "# Pi-config defaults baked into /opt/pi-defaults/; entrypoint seeds them into the user's volume on first run. Tini handles PID 1 signal forwarding."
    )
    .unwrap();
    writeln!(out, "COPY pi-config/ /opt/pi-defaults/").unwrap();
    writeln!(out, "COPY entrypoint.sh /usr/local/bin/entrypoint.sh").unwrap();
    writeln!(out, "USER pi").unwrap();
    writeln!(
        out,
        "ENTRYPOINT [\"/usr/bin/tini\", \"--\", \"/usr/local/bin/entrypoint.sh\"]"
    )
    .unwrap();
    writeln!(out, "CMD [\"pi\"]").unwrap();
    out
}

fn sorted_toolchains(yaml: &YamlOwned) -> BTreeMap<String, String> {
    // BTreeMap yields sort-by-key for free — determinism is structural.
    // All .expect() calls document the validation contract.
    let mapping = yaml.as_mapping().expect("validated by config::load");
    let mut toolchains: Option<&YamlOwned> = None;
    for (key, value) in mapping {
        let name = key.as_str().expect("validated by config::load");
        if name == "toolchains" {
            toolchains = Some(value);
            break;
        }
    }
    let toolchains = toolchains.expect("validated by config::load");
    let toolchains_map = toolchains.as_mapping().expect("validated by config::load");
    toolchains_map
        .iter()
        .map(|(k, v)| {
            let name = k.as_str().expect("validated by config::load");
            let version = v.as_str().expect("validated by config::load");
            (name.to_string(), version.to_string())
        })
        .collect()
}

/// Return the toolchain names from a validated `.pithos` config in
/// alphabetical order. Used by main.rs to assemble the installer-bytes
/// map for fingerprinting; the full `(name, version)` shape stays private
/// to the emitter.
///
/// **Precondition:** `yaml` must be the validated output of
/// [`crate::config::load`]. Same panic contract as [`emit`].
pub fn toolchain_names(yaml: &YamlOwned) -> impl Iterator<Item = String> {
    sorted_toolchains(yaml).into_keys()
}

fn apt_packages(yaml: &YamlOwned) -> Vec<String> {
    // Walk the top-level mapping for `extras`; absent or null → empty.
    // Then walk the extras mapping for `apt`; absent or null → empty.
    // Order is preserved from user input (apt ordering is user-visible).
    let mapping = yaml.as_mapping().expect("validated by config::load");
    let mut extras: Option<&YamlOwned> = None;
    for (key, value) in mapping {
        let name = key.as_str().expect("validated by config::load");
        if name == "extras" {
            extras = Some(value);
            break;
        }
    }
    let Some(extras) = extras else {
        return Vec::new();
    };
    if extras.is_null() {
        return Vec::new();
    }
    let extras_map = extras.as_mapping().expect("validated by config::load");
    let mut apt: Option<&YamlOwned> = None;
    for (key, value) in extras_map {
        let name = key.as_str().expect("validated by config::load");
        if name == "apt" {
            apt = Some(value);
            break;
        }
    }
    let Some(apt) = apt else {
        return Vec::new();
    };
    if apt.is_null() {
        return Vec::new();
    }
    let seq = apt.as_sequence().expect("validated by config::load");
    seq.iter()
        .map(|item| {
            item.as_str()
                .expect("validated by config::load")
                .to_string()
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::emit;
    use crate::config;

    #[test]
    fn entrypoint_sh_exists_at_repo_root() {
        let p = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("entrypoint.sh");
        assert!(
            p.exists(),
            "emitter's COPY entrypoint.sh requires {} to exist",
            p.display()
        );
    }

    #[test]
    fn dotnet_install_sh_exists_at_repo_root() {
        let p =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("toolchains/dotnet-install.sh");
        assert!(
            p.exists(),
            "emitter's COPY toolchains/dotnet-install.sh requires {} to exist",
            p.display()
        );
    }

    #[cfg(unix)]
    #[test]
    fn dotnet_install_sh_is_syntactically_valid_bash() {
        let p =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("toolchains/dotnet-install.sh");
        let status = std::process::Command::new("bash")
            .arg("-n")
            .arg(&p)
            .status()
            .expect("bash must be available to run this test");
        assert!(
            status.success(),
            "bash -n reported a syntax error in {}",
            p.display()
        );
    }

    #[test]
    fn rust_install_sh_exists_at_repo_root() {
        let p = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("toolchains/rust-install.sh");
        assert!(
            p.exists(),
            "emitter's COPY toolchains/rust-install.sh requires {} to exist",
            p.display()
        );
    }

    #[cfg(unix)]
    #[test]
    fn rust_install_sh_is_syntactically_valid_bash() {
        let p = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("toolchains/rust-install.sh");
        let status = std::process::Command::new("bash")
            .arg("-n")
            .arg(&p)
            .status()
            .expect("bash must be available to run this test");
        assert!(
            status.success(),
            "bash -n reported a syntax error in {}",
            p.display()
        );
    }

    #[test]
    fn rust_install_sh_contains_required_install_markers() {
        let p = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("toolchains/rust-install.sh");
        let body = std::fs::read_to_string(&p).expect("rust-install.sh must be readable");
        for marker in [
            "/opt/cargo",
            "/opt/rustup",
            "rustfmt",
            "clippy",
            "chmod -R a+rX",
            "sh.rustup.rs",
            "/etc/profile.d/pithos-rust.sh",
        ] {
            assert!(
                body.contains(marker),
                "rust-install.sh is missing required marker {marker:?}"
            );
        }
    }

    #[test]
    fn go_install_sh_exists_at_repo_root() {
        let p = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("toolchains/go-install.sh");
        assert!(
            p.exists(),
            "emitter's COPY toolchains/go-install.sh requires {} to exist",
            p.display()
        );
    }

    #[cfg(unix)]
    #[test]
    fn go_install_sh_is_syntactically_valid_bash() {
        let p = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("toolchains/go-install.sh");
        let status = std::process::Command::new("bash")
            .arg("-n")
            .arg(&p)
            .status()
            .expect("bash must be available to run this test");
        assert!(
            status.success(),
            "bash -n reported a syntax error in {}",
            p.display()
        );
    }

    #[test]
    fn go_install_sh_contains_required_install_markers() {
        let p = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("toolchains/go-install.sh");
        let body = std::fs::read_to_string(&p).expect("go-install.sh must be readable");
        for marker in [
            "/opt/go",
            "go.dev",
            "mode=json",
            "sha256sum",
            "GOROOT",
            "/etc/profile.d/pithos-go.sh",
        ] {
            assert!(
                body.contains(marker),
                "go-install.sh is missing required marker {marker:?}"
            );
        }
    }

    #[test]
    fn emit_base_only_for_empty_toolchains() {
        // Arrange
        const VALID: &str = "toolchains: {}\n";
        let yaml = config::load(VALID.as_bytes()).unwrap();

        // Act
        let output = emit(&yaml);

        // Assert
        let expected = "\
# Generated by pithos — do not edit
# Base stage: Debian bookworm-slim with Node, Python, uv, Pi CLI, and common dev tools pre-installed.
FROM ghcr.io/anton-kochev/pithos:base AS base
USER root

# Pi-config defaults baked into /opt/pi-defaults/; entrypoint seeds them into the user's volume on first run. Tini handles PID 1 signal forwarding.
COPY pi-config/ /opt/pi-defaults/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
USER pi
ENTRYPOINT [\"/usr/bin/tini\", \"--\", \"/usr/local/bin/entrypoint.sh\"]
CMD [\"pi\"]
";
        assert_eq!(output, expected);
    }

    #[test]
    fn emit_single_toolchain_layer() {
        // Arrange
        const VALID: &str = "toolchains:\n  dotnet: \"10.0.102\"\n";
        let yaml = config::load(VALID.as_bytes()).unwrap();

        // Act
        let output = emit(&yaml);

        // Assert
        let expected = "\
# Generated by pithos — do not edit
# Base stage: Debian bookworm-slim with Node, Python, uv, Pi CLI, and common dev tools pre-installed.
FROM ghcr.io/anton-kochev/pithos:base AS base
USER root

# Toolchain: installed via repo-local script, version pinned from .pithos. Alphabetical order keeps layer cache stable across re-renders.
COPY toolchains/dotnet-install.sh /usr/local/bin/dotnet-install.sh
RUN /usr/local/bin/dotnet-install.sh 10.0.102

# Pi-config defaults baked into /opt/pi-defaults/; entrypoint seeds them into the user's volume on first run. Tini handles PID 1 signal forwarding.
COPY pi-config/ /opt/pi-defaults/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
USER pi
ENTRYPOINT [\"/usr/bin/tini\", \"--\", \"/usr/local/bin/entrypoint.sh\"]
CMD [\"pi\"]
";
        assert_eq!(output, expected);
    }

    #[test]
    fn emit_sorts_toolchains_alphabetically() {
        // Arrange
        const VALID: &str = "toolchains:\n  rust: \"1.85.0\"\n  dotnet: \"10.0.102\"\n";
        let yaml = config::load(VALID.as_bytes()).unwrap();

        // Act
        let output = emit(&yaml);

        // Assert
        let expected = "\
# Generated by pithos — do not edit
# Base stage: Debian bookworm-slim with Node, Python, uv, Pi CLI, and common dev tools pre-installed.
FROM ghcr.io/anton-kochev/pithos:base AS base
USER root

# Toolchain: installed via repo-local script, version pinned from .pithos. Alphabetical order keeps layer cache stable across re-renders.
COPY toolchains/dotnet-install.sh /usr/local/bin/dotnet-install.sh
RUN /usr/local/bin/dotnet-install.sh 10.0.102

COPY toolchains/rust-install.sh /usr/local/bin/rust-install.sh
RUN /usr/local/bin/rust-install.sh 1.85.0

# Pi-config defaults baked into /opt/pi-defaults/; entrypoint seeds them into the user's volume on first run. Tini handles PID 1 signal forwarding.
COPY pi-config/ /opt/pi-defaults/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
USER pi
ENTRYPOINT [\"/usr/bin/tini\", \"--\", \"/usr/local/bin/entrypoint.sh\"]
CMD [\"pi\"]
";
        assert_eq!(output, expected);
    }

    #[test]
    fn emit_all_three_toolchains_exact_match() {
        // Arrange
        const VALID: &str = "\
toolchains:
  dotnet: \"10.0.102\"
  go: \"1.22.0\"
  rust: \"1.85.0\"
";
        let yaml = config::load(VALID.as_bytes()).unwrap();

        // Act
        let output = emit(&yaml);

        // Assert
        let expected = "\
# Generated by pithos — do not edit
# Base stage: Debian bookworm-slim with Node, Python, uv, Pi CLI, and common dev tools pre-installed.
FROM ghcr.io/anton-kochev/pithos:base AS base
USER root

# Toolchain: installed via repo-local script, version pinned from .pithos. Alphabetical order keeps layer cache stable across re-renders.
COPY toolchains/dotnet-install.sh /usr/local/bin/dotnet-install.sh
RUN /usr/local/bin/dotnet-install.sh 10.0.102

COPY toolchains/go-install.sh /usr/local/bin/go-install.sh
RUN /usr/local/bin/go-install.sh 1.22.0

COPY toolchains/rust-install.sh /usr/local/bin/rust-install.sh
RUN /usr/local/bin/rust-install.sh 1.85.0

# Pi-config defaults baked into /opt/pi-defaults/; entrypoint seeds them into the user's volume on first run. Tini handles PID 1 signal forwarding.
COPY pi-config/ /opt/pi-defaults/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
USER pi
ENTRYPOINT [\"/usr/bin/tini\", \"--\", \"/usr/local/bin/entrypoint.sh\"]
CMD [\"pi\"]
";
        assert_eq!(output, expected);
    }

    #[test]
    fn emit_passes_version_verbatim() {
        // Arrange
        const VALID: &str = "toolchains:\n  dotnet: \"10.0.102\"\n";
        let yaml = config::load(VALID.as_bytes()).unwrap();

        // Act
        let output = emit(&yaml);

        // Assert
        assert_eq!(
            output.matches("10.0.102").count(),
            1,
            "version should appear exactly once on the RUN line"
        );
        assert!(
            output.contains("RUN /usr/local/bin/dotnet-install.sh 10.0.102\n"),
            "RUN line with verbatim version missing: {output}"
        );
    }

    #[test]
    fn emit_no_extras_layer_when_extras_absent() {
        // Arrange
        const VALID: &str = "toolchains: {}\n";
        let yaml = config::load(VALID.as_bytes()).unwrap();

        // Act
        let output = emit(&yaml);

        // Assert
        let expected = "\
# Generated by pithos — do not edit
# Base stage: Debian bookworm-slim with Node, Python, uv, Pi CLI, and common dev tools pre-installed.
FROM ghcr.io/anton-kochev/pithos:base AS base
USER root

# Pi-config defaults baked into /opt/pi-defaults/; entrypoint seeds them into the user's volume on first run. Tini handles PID 1 signal forwarding.
COPY pi-config/ /opt/pi-defaults/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
USER pi
ENTRYPOINT [\"/usr/bin/tini\", \"--\", \"/usr/local/bin/entrypoint.sh\"]
CMD [\"pi\"]
";
        assert_eq!(output, expected);
    }

    #[test]
    fn emit_no_extras_layer_when_apt_absent() {
        // Arrange
        const VALID: &str = "toolchains: {}\nextras: {}\n";
        let yaml = config::load(VALID.as_bytes()).unwrap();

        // Act
        let output = emit(&yaml);

        // Assert
        let expected = "\
# Generated by pithos — do not edit
# Base stage: Debian bookworm-slim with Node, Python, uv, Pi CLI, and common dev tools pre-installed.
FROM ghcr.io/anton-kochev/pithos:base AS base
USER root

# Pi-config defaults baked into /opt/pi-defaults/; entrypoint seeds them into the user's volume on first run. Tini handles PID 1 signal forwarding.
COPY pi-config/ /opt/pi-defaults/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
USER pi
ENTRYPOINT [\"/usr/bin/tini\", \"--\", \"/usr/local/bin/entrypoint.sh\"]
CMD [\"pi\"]
";
        assert_eq!(output, expected);
    }

    #[test]
    fn emit_no_extras_layer_when_apt_empty() {
        // Arrange
        const VALID: &str = "toolchains: {}\nextras:\n  apt: []\n";
        let yaml = config::load(VALID.as_bytes()).unwrap();

        // Act
        let output = emit(&yaml);

        // Assert
        let expected = "\
# Generated by pithos — do not edit
# Base stage: Debian bookworm-slim with Node, Python, uv, Pi CLI, and common dev tools pre-installed.
FROM ghcr.io/anton-kochev/pithos:base AS base
USER root

# Pi-config defaults baked into /opt/pi-defaults/; entrypoint seeds them into the user's volume on first run. Tini handles PID 1 signal forwarding.
COPY pi-config/ /opt/pi-defaults/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
USER pi
ENTRYPOINT [\"/usr/bin/tini\", \"--\", \"/usr/local/bin/entrypoint.sh\"]
CMD [\"pi\"]
";
        assert_eq!(output, expected);
    }

    #[test]
    fn emit_extras_layer_with_no_toolchains() {
        // Arrange
        const VALID: &str = "toolchains: {}\nextras:\n  apt: [git]\n";
        let yaml = config::load(VALID.as_bytes()).unwrap();

        // Act
        let output = emit(&yaml);

        // Assert
        let expected = "\
# Generated by pithos — do not edit
# Base stage: Debian bookworm-slim with Node, Python, uv, Pi CLI, and common dev tools pre-installed.
FROM ghcr.io/anton-kochev/pithos:base AS base
USER root

# Extras: apt packages from .pithos. Installed after toolchains so editing the package list does not invalidate toolchain layers.
RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*

# Pi-config defaults baked into /opt/pi-defaults/; entrypoint seeds them into the user's volume on first run. Tini handles PID 1 signal forwarding.
COPY pi-config/ /opt/pi-defaults/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
USER pi
ENTRYPOINT [\"/usr/bin/tini\", \"--\", \"/usr/local/bin/entrypoint.sh\"]
CMD [\"pi\"]
";
        assert_eq!(output, expected);
    }

    #[test]
    fn emit_extras_layer_after_toolchains() {
        // Arrange
        const VALID: &str = "\
toolchains:
  dotnet: \"10.0.102\"
extras:
  apt: [git, libssl3]
";
        let yaml = config::load(VALID.as_bytes()).unwrap();

        // Act
        let output = emit(&yaml);

        // Assert
        let expected = "\
# Generated by pithos — do not edit
# Base stage: Debian bookworm-slim with Node, Python, uv, Pi CLI, and common dev tools pre-installed.
FROM ghcr.io/anton-kochev/pithos:base AS base
USER root

# Toolchain: installed via repo-local script, version pinned from .pithos. Alphabetical order keeps layer cache stable across re-renders.
COPY toolchains/dotnet-install.sh /usr/local/bin/dotnet-install.sh
RUN /usr/local/bin/dotnet-install.sh 10.0.102

# Extras: apt packages from .pithos. Installed after toolchains so editing the package list does not invalidate toolchain layers.
RUN apt-get update && apt-get install -y --no-install-recommends git libssl3 && rm -rf /var/lib/apt/lists/*

# Pi-config defaults baked into /opt/pi-defaults/; entrypoint seeds them into the user's volume on first run. Tini handles PID 1 signal forwarding.
COPY pi-config/ /opt/pi-defaults/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
USER pi
ENTRYPOINT [\"/usr/bin/tini\", \"--\", \"/usr/local/bin/entrypoint.sh\"]
CMD [\"pi\"]
";
        assert_eq!(output, expected);
    }

    #[test]
    fn emit_extras_preserves_user_order() {
        // Arrange
        const VALID: &str = "toolchains: {}\nextras:\n  apt: [libssl3, git]\n";
        let yaml = config::load(VALID.as_bytes()).unwrap();

        // Act
        let output = emit(&yaml);

        // Assert
        let expected = "\
# Generated by pithos — do not edit
# Base stage: Debian bookworm-slim with Node, Python, uv, Pi CLI, and common dev tools pre-installed.
FROM ghcr.io/anton-kochev/pithos:base AS base
USER root

# Extras: apt packages from .pithos. Installed after toolchains so editing the package list does not invalidate toolchain layers.
RUN apt-get update && apt-get install -y --no-install-recommends libssl3 git && rm -rf /var/lib/apt/lists/*

# Pi-config defaults baked into /opt/pi-defaults/; entrypoint seeds them into the user's volume on first run. Tini handles PID 1 signal forwarding.
COPY pi-config/ /opt/pi-defaults/
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
USER pi
ENTRYPOINT [\"/usr/bin/tini\", \"--\", \"/usr/local/bin/entrypoint.sh\"]
CMD [\"pi\"]
";
        assert_eq!(output, expected);
    }
}
